### ISSUE TITLE
old data raise error

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ruvnl-consumer-app#10]
## Detailed Description
If the data is more than 1 hour old, then we should raise an error

## Context
- solar data doesnt update in the night, so only raise error if wind data is old
- could not raise error if its nighttime for solar data

## Possible Implementation
- Only raise error if wind data is old, to keep it simple
- https://github.com/openclimatefix/ruvnl-consumer-app/blob/main/ruvnl_consumer_app/app.py#L89

**Comment by peterdudfield** [comment]
Run the code locally with `python ruvnl_consumer_app/app.py`

**Comment by dantravers** [comment]
Where is the error to be raised?

**Comment by peterdudfield** [comment]
Error will be raised in the bit of code. This means we can see that this micro services will have failed and will show up on Airflow. This then can be then triggered a slack notification e.t.c
