### ISSUE TITLE
India: runvnl consumer not running regulary

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ruvnl-consumer-app#8]
## Detailed Description
It looks like there are some gaps in the data, need to look why this has happened

## Context
- could be something to do with the way things are merged in the database, https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/write/generation.py#L53
- Airflow should run the task every 3 mins

## Possible Implementation
not sure

**Comment by confusedmatrix** [comment]
I suggest this be closed if the issue is the underlying API
